### ISSUE TITLE
memory leak isssue

### ISSUE THREAD

**Issue by Maxh1989** [BruceSherwood/glowscript#157]
Just curious about an issue I get when running the GlowscriptOfflline locally.  I end up getting a memory leak. Every time you hit run button then you get a bunch of JavaScript objects that don't clean themselves up. Maybe I'm doing something wrong, but just curious if anyone as run into this issue.

**Comment by BruceSherwood** [comment]
From the GlowScriptOffline README file (I don't know yet how to avoid the problem):

POSSIBLE SLOWDOWN
If you make a large number of runs, performance may degrade due to an accumulation of "WebGL contexts". However, there is a simple remedy: reload the web page.
