### ISSUE TITLE
compiler throws nonsensical exception under firefox

### ISSUE THREAD

**Issue by JohnDenker** [BruceSherwood/glowscript#20]
In addition to all the problems discussed in item #19,  firefox has additional problems.

After a syntax error, the compiler terminates by throwing an exception.  Unlike chrome, which throws a semi-informative message, firefox throws "window.__original is undefined"

That makes no sense, several times over.
* First of all, the compiler should never ever mess with the window.
* Secondly, it throws that message even if window.__original was defined in the environment of the compiler.
* It's very peculiar that chrome and firefox behave differently.

Some constructive suggestions are discussed in item #19.

**Comment by BruceSherwood** [comment]
Again, none of this happens in other uses of the compiler.
