### ISSUE TITLE
compiler trashes javascript console under firefox

### ISSUE THREAD

**Issue by JohnDenker** [BruceSherwood/glowscript#21]
The following is observed in the firefox environment.  (Chrome behaves normally.)

In the situation outlined in item #19, then the compiler terminates, the javascript console is cleared.  This is bad.  Furthermore, any subsequent attempts to write to the javascript console have no discernible effect.  This is even worse.

I suppose this could be considered a firefox bug rather than a compiler bug, but I reckon there is enough blame to go around.  The compiler should please refrain from doing whatever contributes to causing this problem.

**Comment by BruceSherwood** [comment]
Doesn't happen with other uses of the compiler.
