### ISSUE TITLE
import random, very odd failure, contrary to documentation

### ISSUE THREAD

**Issue by JohnDenker** [BruceSherwood/glowscript#22]
Repeatedly I've been told to read the glowscript documentation.  So let's try that and see what happens:   On page 
>     http://www.glowscript.org/docs/GlowScriptDocs/VPython-vs-GlowScript.html

it says 
>     Full documentation of RapydScript is available at http://rapydscript.pyjeon.com.

Then  on page
>     http://www.rapydscript.com/modules-and-imports-2/

it says 
>    In addition to JavaScript-like import of including in your code and having
>    RapydScript use that logic directly, libraries written in RapydScript itself
>    can be imported as easily as in Python.

and it cites "import random" as an example.

So it must be easy, right?  In particular, it must be easy to "import random". I know it must be easy, because the documentation says so.

When I do the experiment, I observe that "import random" produces no errors and no warnings from the compiler.  The compiler produces code that "almost" works.  It gets quite a ways into the program before dying.  It dies without printing any messages in any place I know about, and without throwing an exception.  It just stops execution.

This misbehavior is 100% reproducible chez moi.  It is the same under both chrome and firefox.

This bug (and a number of others) can be demonstrated with the help of
    https://www.av8n.com/physics/glorpy-demo.html
or equivalently (with less security)
    http://www.av8n.com/physics/glorpy-demo.html
Just uncomment the "import random" and see what happens.

**Comment by BruceSherwood** [comment]
Thanks for the report about what's said in the RapydScript documentation. What this sounds like is that there exists a random module usable with RapydScript, but that I don't have that library. In the particular case of "random" there is this from the GlowScript VPython Help section on built-in math functions:

random()   # pseudorandom number 0 to 1

**Comment by JohnDenker** [comment]
1) FWIW random.pyj can be found at
    https://github.com/atsepkov/RapydScript/blob/master/src/lib/random.pyj

2) OTOH, even though the "import random" example is particularly meaningful because it comes straight out of the documentation, the root of the problem lies much deeper.  A less-meaningful statement such as 

    import coals_to_newcastle

produces the same bizarre symptoms:  No compile-time errors or warnings, no run-time errors or warnings, just code that fails to execute correctly.  The point of failure is nowhere near the location of the import statement.

**Comment by BruceSherwood** [comment]
Good point. There is some special handling of the import statement to accept "import visual", to facilitate bringing an existing classic VPython program into the browser, and that code should do something sensible when encountering an import it can't currently deal with. Thanks.

**Comment by BruceSherwood** [comment]
The import machinery is much improved, including that "import coals_to_newcastle" gives an error.
