### ISSUE TITLE
constant strings are being adulterated

### ISSUE THREAD

**Issue by JohnDenker** [BruceSherwood/glowscript#23]
Here's another chip off the tip of the iceberg:
>    print(len('&amp;'), '&amp;')

When I run regular old python from the command line, it prints  "1 &amp;" as one might expect.  However, the browser-based thing prints "5 &amp;amp;" which is not the result that ordinary mortals were expecting.

It's not even entirely obvious how to work around this "hurdle".

I suppose I could get an ampersand into the program using chr(38) ... now that I have implemented my own ord() and chr() functions from scratch ... but that doesn't solve the problem for general strings, especially when trying to port pre-existing code.

Ampersand is not the only character affected.  Greater-than and less-than suffer a similar fate.  Not being able to use such characters in the ordinary way is a tremendous hassle.

Suggestion:  Leave the strings alone!

**Comment by BruceSherwood** [comment]
I'm not altering the strings. I'm adding them to a textarea, and evidently the textarea is doing something neither you nor I want. Thanks for the report.

**Comment by JohnDenker** [comment]
The obvious solution is to avoid roundtripping stuff to/from HTML nodes.  I imagine most of what needs to be done can be done using plain old javascript variables.

=================

If for some reason  you absolutely have to stick stuff in HTML nodes, you might consider using   .textContent   in place of .innerHTML 

Reference: https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent    

Look for the key phrase "the text is not parsed as HTML".  I don't guarantee this will do what you want ... but some simple experiments will tell the tale.

This requires a moderately modern browser.

**Comment by JohnDenker** [comment]
Also of interest:  <XMP> nodes.

I switched my demo code to use <XMP> in critical places, and to use .textContent ....  This helps a lot.  In all likelihood, this was a bug in my code all along, not in the compiler, so this item #23 should be closed as invalid.  If the bug crops up again, I'll submit a new and better-focused report.

**Comment by BruceSherwood** [comment]
Okay, I'll close this. Thanks.
