### ISSUE TITLE
try/except blocks don't compile

### ISSUE THREAD

**Issue by JohnDenker** [BruceSherwood/glowscript#24]
Contrary to what it says in the rapydscript documentation,
  http://rapydscript.pyjeon.com/
try/except blocks don't compile correctly in the browser environment.  They are equally unusable under firefox and chrome.

Of all the things that need to work, this is high on the list.  Lots of other nastiness can be worked around by using try/catch blocks.

**Comment by BruceSherwood** [comment]
Interesting, and puzzling. I don't know of anything I'm doing that would break something that RapydScript supports. Thanks for the report.

**Comment by BruceSherwood** [comment]
It's a fixable GlowScript bug having to do with inserting line numbers into the "binary", to provide information in case of an error.

**Comment by BruceSherwood** [comment]
Fixed.
