### ISSUE TITLE
keydown event: charCode broken

### ISSUE THREAD

**Issue by JohnDenker** [BruceSherwood/glowscript#25]
When somebody types a key on the keyboard, the event-object (of type 'keydown') has a charCode of 0.  I find this to be undocumented, unobvious, and unhelpful, to say the least.  (The "keyCode" and the "which" are nonzero, but that's the answer to a different question.)

The problem is observed under both chrome and firefox.

This shouldn't be too hard to fix;  after all, javascript knows the correct charCode.

**Comment by BruceSherwood** [comment]
I thought key processing was working, so maybe something has come loose. Thanks.

**Comment by JohnDenker** [comment]
The more-or-less standard way to deal with this is to combine information from the low-level javascript events: keydown **and** keypress.  That is, the keydown event has a keyCode value, so save it.  Wait for the keypress event, which has a charCode value.  Then you can return both.   (You can get by with less work than this in *some* browsers, but not in the general case.)

There is code in ace/ace.js that appears to know about this.  However, the code in glow/canvas.js didn't get the memo. 

Note that the python interface quite properly does not expose the keypress event to users.  I am emphatically not suggesting changing this.  Only the combination should be exposed ... and keydown is a good-enough name for the combination.  The distinction between keydown and keypress is exactly the sort of nonsense that the high-level language should protect users from.  The code in canvas.js already goes to considerable trouble to protect users from browser misbehavior, e.g. by reconstructing the "key" value (which chrome should provide but doesn't).

Testing this is a horror show:
* keydown versus keypress
* firefox versus chrome versus ie .....
* e.keyCode versus e.charCode versus e.which versus e.key
* et cetera

**Comment by JohnDenker** [comment]
Easier and better solution.  One line patch, speaks for itself.

```
commit 2806fca6be0d6cac7bf4903f0a52699b4b13190b
Author: John Denker <jsd@av8n.com>
Date:   Fri Sep 11 09:27:50 2015 -0700

    make charCode work for keyboard events

diff --git a/lib/glow/canvas.js b/lib/glow/canvas.js
index d5ee823..2b4ff45 100644
--- a/lib/glow/canvas.js
+++ b/lib/glow/canvas.js
@@ -215,6 +215,7 @@
                ev.key = _unshifted[ev.which]
                if (shiftlock && (65 <= ev.which && ev.which <= 90)) ev.key = _shifted[ev.which]
                else if (canvas.mouse.shift) ev.key = _shifted[ev.which]
+                if (ev.key.length == 1) ev.charCode = ev.key.charCodeAt(0)
                ev.alt = canvas.mouse.alt
                ev.ctrl = canvas.mouse.ctrl
                // The statement "canvas.trigger(ev.type, ev)" is needed to make keyboard events work,
```
