### ISSUE TITLE
 scene.bind('keydown', ) behaving more like document.bind()

### ISSUE THREAD

**Issue by JohnDenker** [BruceSherwood/glowscript#26]
In the context of scene.bind('keydown', handler)  the handler seems to receive events from all over the document ... not just from the scene.

This stands in contrast to mouse events, which are only generated from strictly inside the scene.

This may seem like a small thing, but it actually causes some serious usability problems.

The problem is observed equally under firefox and chrome.

**Comment by BruceSherwood** [comment]
Thanks for spotting this. Very recently I fixed a problem that mouse events were going to the whole document, but I failed to notice that the same problem afflicts key events.
