### ISSUE TITLE
(1,0,1) instead of vector(1,0,1) fails miserably

### ISSUE THREAD

**Issue by JohnDenker** [BruceSherwood/glowscript#27]
Apparently the browser-based compiler won't allow box(color=(1, 0, 1))
Apparently one must say box(color=vector(1, 0, 1))
This is a tremendous nuisance when trying to port existing code.

Just using the list instead of the vector does not produce an error message in any place that I know of, and does not throw an exception. ...  just silent failure.  This magnifies the pain factor enormously.

Users need specific, informative error messages.  Students double-especially so.

**Comment by BruceSherwood** [comment]
This gives a clear error message in the glowscript.org environment. Your experimental environment is missing this error handling machinery. The key element is the function reportScriptError() in untrusted/run.js.
