### ISSUE TITLE
documentation:  python <--> javascript <--> HTML DOM

### ISSUE THREAD

**Issue by JohnDenker** [BruceSherwood/glowscript#28]
This is a documentation issue.

It wasn't obvious to me how to interface from python to the HTML DOM, for instance when changing the style  of a textarea.  Eventually I discovered that it is OK, apparently, for the python program to say
>         py_win.style.height = '300px'

even though py_win was not declared within the  python code;  it was defined in the javascript environment and 'inherited' by the python system.  Someone who didn't know how the thing is built internally would find that highly non-obvious.  Other languages don't work that way.  For instance, when I am programming in C++ or python, if I want to look at the environment of another programming (perhaps the shell), I have to ask politely (perhaps via argv) ... and if I want to change the other guy's environment it's generally not allowed.  Similarly, calling C++ from assembly language (or vice versa) is highly nontrivial.  I have good reasons to think of asm.js as assembly language, and if that's not right, the relationships need to be documented.

It may be obvious to the guy who designed the system that it blurs the line between python and javascript, but it's not *a priori* obvious to other folks.  This sort of thing needs to be documented, preferably with examples.

Just saying "it's a hybrid" or "the lines are blurred" is not sufficient, because nobody knows which lines are blurred and which are not.

**Comment by BruceSherwood** [comment]
Do look at some examples, such as 

http://www.glowscript.org/#/user/GlowScriptDemos/folder/Examples/program/ButtonsSlidersMenus-VPython

Also, note that the browser environment has a large number of true globals which, as far as I know, cannot be kept out of your own namespace.

**Comment by JohnDenker** [comment]
I wouldn't have said non-python names "cannot be kept out".  There are 100 ways of keeping namespaces separate, if you wanted to.  One of the most obvious ways is munging the names:  Then a python statement such as:

    xx=yy(zz)    # python

could be represented in the assembly.js code emitted by the compiler as:

    rump_L_stilt__xx = rump_L_stilt__yy(rump_L_stilt__zz)   // js

or could be localized within a structure:

    rump_L_stilt__ . xx = rump_L_stilt__ . yy(rump_L_stilt__ . zz)  // js

Wrappers would be needed if/whenever it was desired to import something from other environments.  Compilers have been doing this sort of thing for many decades.  Doing it for good reasons.

The fact that the in-browser compiler system chooses not to do things this way is an engineering choice, not a law of nature.  It would be absurd to imagine that such things "go without saying" and don't need to be documented.

I was asked what hassles, hurdles, and sources of confusion I faced.  This was one of them.
