### ISSUE TITLE
incorrect exception throwing in lib/compiler.js 

### ISSUE THREAD

**Issue by JohnDenker** [BruceSherwood/glowscript#29]
In lib/compiler.js there are about six instances of "throw new Error(....)"

AFAICT all but one of them are wrong.  This makes the thrown messages significantly less informative than they should be.

Please review the meaning of the three arguments:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error

**Comment by BruceSherwood** [comment]
Curious. I thought those had been tested. Will look. Thanks.
