### ISSUE TITLE
even if not executed, any "import" does the opposite of "import visual"

### ISSUE THREAD

**Issue by JohnDenker** [BruceSherwood/glowscript#32]
This can be considered a generalization, elaboration, and clarification of item #22.  I spent a bunch of time looking into the issue, so I could provide a more informative report.

Observed behavior
-----------------------
1) Ironically enough, an "import visual" statement does exactly the opposite of what you would expect:  It causes a number of graphics-related symbols that otherwise would have been defined to be left undefined.  You can easily see what's happening by comparing the generated code, with and without the import statement.

2) For that matter, any import statement has the same effect, no matter what library is mentioned.

3) What's worse, an import statement that never gets executed has the same effect.  To demonstrate this, use an import statement governed by an "if 0:" statement.

4) Under no conditions AFAICT does an import statement generate a compile-time warning or error.  This includes cases where the library in question should exist, as well as cases where it doesn't exist.

To say the same thing another way:  an import statement does not generate any executable code at the location of the statement, no matter whether it is governed by a conditional or not.  All it does is cause a bunch of symbols to not get defined.

This could be considered three or four different bugs, but I'm lumping them together because it seems likely that the root cause is the same for all.  Anybody who wants to split them into separate tracker issues is welcome to do so.

Expected and Desired Behavior
=======================

It would be nice if the import statement actually worked, i.e. actually imported libraries.  A number of useful libraries exist, useful and usable in this context.

**Comment by BruceSherwood** [comment]
It is true that this area is severely underdeveloped. I attempted to do some minimal processing to handle common cases of import in legacy classic VPython code, but I wouldn't be surprised if there are bugs there. At the moment the only mechanism for importing (JavaScript) modules is the get_library() function in GlowScript. Here's a particularly spectacular example, due to a colleague:

http://www.glowscript.org/#/user/Bruce_Sherwood/folder/Pub/program/oimo-falling-spheres

**Comment by BruceSherwood** [comment]
Judging from the html file you sent me, which contains VPython source code to be compiled and executed, wouldn't it make more sense simply to add <script> elements for the JavaScript libraries you want to use? Why would you use "import"?

**Comment by BruceSherwood** [comment]
1) "import visual" or "import vis" does what it does in standard Python: to show a box, you have to say visual.box() or vis.box(). I don't think this is a change. Issues 2, 3, and 4 are still open.

**Comment by BruceSherwood** [comment]
The import machinery has been overhauled, including giving an error on "import coals._to_newcastle".

What looks strange about undefining symbols is that this is the only way within the existing GlowScript structure to eliminate unwanted symbols in the presence of a restrictive import.
