### ISSUE TITLE
unimplemented : multiply sequence by scalar

### ISSUE THREAD

**Issue by JohnDenker** [BruceSherwood/glowscript#35]
Expected and desired behavior
---------------------------------------

Multiplying a sequence by a scalar produces N copies of the sequence.  As I understand it, this is a basic, standard python feature:

```
python
>>> ["x"] * 5
['x', 'x', 'x', 'x', 'x']
>>> 
```

Reference e.g.: http://learning-python.com/class/Workbook/unit03.htm

Observed behavior
------------------------

The browser-based compiler doesn't seem to know about this.  It says:

    Runtime error: '[0]['*'] is not a function'

**Comment by JohnDenker** [comment]
Also:  It looks like addition of sequences isn't implemented either:

    python
    >>> [1, 2] + ['x']
    [1, 2, 'x']

HOWEVER, both of these issues (addition and multiplication) are almost trivial to fix.
I have code that fixes most of the cases, if anybody's interested.

**Comment by BruceSherwood** [comment]
These are RapydScript issues.
