### ISSUE TITLE
print(nested_list) does the wrong thing

### ISSUE THREAD

**Issue by JohnDenker** [BruceSherwood/glowscript#39]
#### Context

```
#! /usr/bin/python3
nested_list = [ [1, 2], [3, 4] ]
print(nested_list)
```

#### Expected and Desired Behavior (standard python)

```
[[1, 2], [3, 4]]
```

#### Observed Behavior (in the browser)

```
[1,2, 3,4]
```

**Comment by BruceSherwood** [comment]
This one looks fixable. For the record, the print function is in the file lib/glow/api_misc.js.

**Comment by BruceSherwood** [comment]
Fixed.
