### ISSUE TITLE
Labels don't follow touchscreen 2-finger spin

### ISSUE THREAD

**Issue by wigie** [BruceSherwood/glowscript#49]
On a touchscreen interface, when using a two-finger gesture to spin or twirl the scene
(i.e., spinning the camera about its forward axis), labels don't move with the rest of the scene.
The labels snap back into their correct places if you follow the twirl with a pinch-zoom or a swipe-rotate.

(Tested only on iOS devices with Chrome and Safari browsers, so unsure if this is a platform-specific problem.)

**Comment by BruceSherwood** [comment]
Fixed in upcoming GlowScript 2.1. Thanks for the report!
