### ISSUE TITLE
Changing canvas width or height after canvas activation

### ISSUE THREAD

**Issue by BruceSherwood** [BruceSherwood/glowscript#52]
If a canvas width or height is changed after activation (due to an object needing to be displayed) mouse picking does not work properly. What needs to be done is that when canvas width or height changes the size of the mouse picking texture memory needs to be changed accordingly.

**Comment by thehappyt** [comment]
I figured out what was wrong here. In the current code, the textures are being re-initialized each time the width or height changes. The buffers (frame and render/depth) also depend on width and height, but are not being re-initialized.

Just add the following lines of code in the **if** statement starting on **line 451** of the current WebGLRenderer.js file:
`gl.bindFramebuffer(gl.FRAMEBUFFER, peelFramebuffer);`
`gl.bindRenderbuffer(gl.RENDERBUFFER, peelRenderbuffer);`
`gl.renderbufferStorage(gl.RENDERBUFFER, gl.DEPTH_COMPONENT16, ktexture*canvas.__width, ktexture*canvas.__height);`
`gl.framebufferRenderbuffer(gl.FRAMEBUFFER, gl.DEPTH_ATTACHMENT, gl.RENDERBUFFER, peelRenderbuffer);`
`gl.bindRenderbuffer(gl.RENDERBUFFER, null);`
`gl.bindFramebuffer(gl.FRAMEBUFFER, null);`
