### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by iblis17** [BruceSherwood/glowscript#53]
H!
Is there any instruction for building this repo?
I want to run this IDE on my own server.

Also, I am curious that where is the LICENSE info?

**Comment by BruceSherwood** [comment]
The license is found at lib/glow/LICENSE.txt; you're right, it should be much more prominent.

This is a Google App Engine application. Here are instructions for running locally, using a local server, which is related to your question:

http://www.glowscript.org/docs/GlowScriptDocs/local.html

We used Google mechanisms to set up glowscript.org, but I assume (without actual knowledge) that it would not be difficult to set up your own server.

**Comment by iblis17** [comment]
@BruceSherwood Thanks for your reply!
