### ISSUE TITLE
export glowscript html needs changes to pass xml validation

### ISSUE THREAD

**Issue by atitus** [BruceSherwood/glowscript#63]
The exported HTML in the file ide.js needs the following changes in order to produce valid xml:

1. The line:

<link href="http://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet" type="text/css">

needs /> to close the link tag.

2. For the tag:

<script type="text/javascript">
...
</script>

Replace with:

<script type="text/javascript"><![CDATA[//><!]]></script>

**Comment by BruceSherwood** [comment]
Thanks much for the detailed report and fix!
