### ISSUE TITLE
(-1 < 0) == (1 < 0) is True

### ISSUE THREAD

**Issue by prprprpony** [BruceSherwood/glowscript#71]
[link](http://www.glowscript.org/#/user/pr3pony/folder/Public/program/bool-compare-bug)
code
```
GlowScript 2.7 VPython
print((-1<0),(1<0),(-1 < 0) == (1 < 0))
if (-1 < 0) == (1 < 0) is True:
    print('hi')
x=(-1<0)
y=(1<0)
print(x,y,x == y)
```

optput
```
true false true
hi
true false false
```

**Comment by BruceSherwood** [comment]
Thanks for the clear error report. I've passed this on to the RapydScript-NG developer (RapydScript-NG is used by GlowScript VPython to convert Python to JavaScript).

**Comment by BruceSherwood** [comment]
Fixed. Kovid Goyal, the developer of RapydScript-NG is incredibly fast in dealing with bugs.
